"""add_sentence_text_to_slr

Revision ID: 01e5dc85d259
Revises: 3f794a205cbd
Create Date: 2026-01-02 23:10:01.492348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e5dc85d259'
down_revision: Union[str, Sequence[str], None] = '3f794a205cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_learning_records', sa.Column('sentence_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentence_learning_records', 'sentence_text')
    # ### end Alembic commands ###
