"""Add WordProficiency table

Revision ID: 025f95a766c9
Revises: a676ad607415
Create Date: 2025-12-27 14:14:56.049083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025f95a766c9'
down_revision: Union[str, Sequence[str], None] = 'a676ad607415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_proficiency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('exposure_count', sa.Integer(), nullable=False),
    sa.Column('huh_count', sa.Integer(), nullable=False),
    sa.Column('continue_count', sa.Integer(), nullable=False),
    sa.Column('difficulty_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proficiency_difficulty', 'word_proficiency', ['difficulty_score'], unique=False)
    op.create_index('idx_proficiency_user_word', 'word_proficiency', ['user_id', 'word'], unique=False)
    op.create_index(op.f('ix_word_proficiency_word'), 'word_proficiency', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_proficiency_word'), table_name='word_proficiency')
    op.drop_index('idx_proficiency_user_word', table_name='word_proficiency')
    op.drop_index('idx_proficiency_difficulty', table_name='word_proficiency')
    op.drop_table('word_proficiency')
    # ### end Alembic commands ###
