"""add_vocab_learning_log_table

Revision ID: 0d3c2471aaff
Revises: e2337545152d
Create Date: 2025-12-29 11:52:30.369138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3c2471aaff'
down_revision: Union[str, Sequence[str], None] = 'e2337545152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_learning_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('audio_timestamp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vocab_log_source', 'vocab_learning_logs', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_vocab_log_user_word', 'vocab_learning_logs', ['user_id', 'word'], unique=False)
    op.create_index(op.f('ix_vocab_learning_logs_user_id'), 'vocab_learning_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocab_learning_logs_word'), 'vocab_learning_logs', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_learning_logs_word'), table_name='vocab_learning_logs')
    op.drop_index(op.f('ix_vocab_learning_logs_user_id'), table_name='vocab_learning_logs')
    op.drop_index('idx_vocab_log_user_word', table_name='vocab_learning_logs')
    op.drop_index('idx_vocab_log_source', table_name='vocab_learning_logs')
    op.drop_table('vocab_learning_logs')
    # ### end Alembic commands ###
