"""add category and itunes_id to podcast_feeds

Revision ID: 118505373969
Revises: 2db6898c82a8
Create Date: 2026-01-24 15:40:30.430466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118505373969'
down_revision: Union[str, Sequence[str], None] = '2db6898c82a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_podcast_episodes_guid'), 'podcast_episodes', ['guid'], unique=False)
    op.add_column('podcast_feeds', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('podcast_feeds', sa.Column('itunes_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'podcast_feeds', ['itunes_id'])
    op.create_index(op.f('ix_podcast_listening_sessions_user_id'), 'podcast_listening_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_episode_states_user_id'), 'user_episode_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_episode_states_user_id'), table_name='user_episode_states')
    op.drop_index(op.f('ix_podcast_listening_sessions_user_id'), table_name='podcast_listening_sessions')
    op.drop_constraint(None, 'podcast_feeds', type_='unique')
    op.drop_column('podcast_feeds', 'itunes_id')
    op.drop_column('podcast_feeds', 'category')
    op.drop_index(op.f('ix_podcast_episodes_guid'), table_name='podcast_episodes')
    # ### end Alembic commands ###
