"""add_podcast_tables

Revision ID: 2db6898c82a8
Revises: b556280e8122
Create Date: 2026-01-21 22:10:20.178719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db6898c82a8'
down_revision: Union[str, Sequence[str], None] = 'b556280e8122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Shared Podcast Feeds (No user_id)
    op.create_table('podcast_feeds',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('rss_url', sa.Text(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('author', sa.Text(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('website_url', sa.Text(), nullable=True),
        sa.Column('etag', sa.String(length=255), nullable=True),
        sa.Column('last_fetched_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('rss_url')
    )
    op.create_index('idx_podcast_feed_url', 'podcast_feeds', ['rss_url'], unique=False)

    # 2. User Subscriptions (Many-to-Many: User <-> Feed)
    op.create_table('podcast_feed_subscriptions',
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('feed_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['feed_id'], ['podcast_feeds.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    op.create_index('idx_pfs_user', 'podcast_feed_subscriptions', ['user_id'], unique=False)

    # 3. Episodes (Belong to Feed, Global)
    op.create_table('podcast_episodes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('feed_id', sa.Integer(), nullable=False),
        sa.Column('guid', sa.Text(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('audio_url', sa.Text(), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('transcript_text', sa.Text(), nullable=True),
        sa.Column('transcript_status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['feed_id'], ['podcast_feeds.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_podcast_episode_feed', 'podcast_episodes', ['feed_id'], unique=False)
    op.create_index('idx_podcast_episode_guid', 'podcast_episodes', ['guid'], unique=False)
    op.create_index('idx_podcast_episode_pub', 'podcast_episodes', ['published_at'], unique=False)

    # 4. User Episode States (Resume position, Finished status)
    op.create_table('user_episode_states',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('episode_id', sa.Integer(), nullable=False),
        sa.Column('current_position_seconds', sa.Float(), server_default='0', nullable=False),
        sa.Column('is_finished', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('listened_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False), # For "Recently Played"
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['episode_id'], ['podcast_episodes.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'episode_id', name='uq_user_episode_state')
    )
    op.create_index('idx_ues_user_listened', 'user_episode_states', ['user_id', 'listened_at'], unique=False)

    # 5. Listening Sessions (History Logs for Analytics)
    op.create_table('podcast_listening_sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('episode_id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('total_listened_seconds', sa.Integer(), nullable=False),
        sa.Column('last_position_seconds', sa.Float(), nullable=False), # Position at end of specific session
        sa.ForeignKeyConstraint(['episode_id'], ['podcast_episodes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pls_user_started', 'podcast_listening_sessions', ['user_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pls_user_started', table_name='podcast_listening_sessions')
    op.drop_table('podcast_listening_sessions')

    op.drop_index('idx_ues_user_listened', table_name='user_episode_states')
    op.drop_table('user_episode_states')

    op.drop_index('idx_podcast_episode_pub', table_name='podcast_episodes')
    op.drop_index('idx_podcast_episode_guid', table_name='podcast_episodes')
    op.drop_index('idx_podcast_episode_feed', table_name='podcast_episodes')
    op.drop_table('podcast_episodes')

    op.drop_index('idx_pfs_user', table_name='podcast_feed_subscriptions')
    op.drop_table('podcast_feed_subscriptions')

    op.drop_index('idx_podcast_feed_url', table_name='podcast_feeds')
    op.drop_table('podcast_feeds')
    # ### end Alembic commands ###
