"""add_reading_sessions_table

Revision ID: 39754ef844df
Revises: fc69483661a7
Create Date: 2025-12-30 09:08:49.644280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39754ef844df'
down_revision: Union[str, Sequence[str], None] = 'fc69483661a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('article_title', sa.Text(), nullable=True),
    sa.Column('total_word_count', sa.Integer(), nullable=False),
    sa.Column('total_sentences', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_active_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('max_sentence_reached', sa.Integer(), nullable=False),
    sa.Column('total_active_seconds', sa.Integer(), nullable=False),
    sa.Column('total_idle_seconds', sa.Integer(), nullable=False),
    sa.Column('word_click_count', sa.Integer(), nullable=False),
    sa.Column('scroll_jump_count', sa.Integer(), nullable=False),
    sa.Column('reading_quality', sa.Text(), nullable=True),
    sa.Column('validated_word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reading_sessions_source', 'reading_sessions', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_reading_sessions_user', 'reading_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reading_sessions_user', table_name='reading_sessions')
    op.drop_index('idx_reading_sessions_source', table_name='reading_sessions')
    op.drop_table('reading_sessions')
    # ### end Alembic commands ###
