"""add_interaction_log_to_slr

Revision ID: 3f794a205cbd
Revises: 72f20468f2be
Create Date: 2026-01-02 21:47:50.374463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f794a205cbd'
down_revision: Union[str, Sequence[str], None] = '72f20468f2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_learning_records', sa.Column('interaction_log', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentence_learning_records', 'interaction_log')
    # ### end Alembic commands ###
