"""add_review_system_tables

Revision ID: 4f0adbca8a15
Revises: 552a79d1e801
Create Date: 2026-01-04 07:58:15.844359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0adbca8a15'
down_revision: Union[str, Sequence[str], None] = '552a79d1e801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=False),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('highlighted_items', sa.JSON(), nullable=False),
    sa.Column('difficulty_type', sa.Text(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_source', 'review_items', ['source_id', 'sentence_index'], unique=False)
    op.create_index('idx_review_user_next', 'review_items', ['user_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_review_items_user_id'), 'review_items', ['user_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_item_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('interval_at_review', sa.Float(), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_item', 'review_logs', ['review_item_id'], unique=False)
    op.create_index('idx_log_reviewed_at', 'review_logs', ['reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_log_reviewed_at', table_name='review_logs')
    op.drop_index('idx_log_item', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_review_items_user_id'), table_name='review_items')
    op.drop_index('idx_review_user_next', table_name='review_items')
    op.drop_index('idx_review_source', table_name='review_items')
    op.drop_table('review_items')
    # ### end Alembic commands ###
