"""add_llm_cache_tables

Revision ID: 552a79d1e801
Revises: 01e5dc85d259
Create Date: 2026-01-03 20:16:42.880839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "552a79d1e801"
down_revision: Union[str, Sequence[str], None] = "01e5dc85d259"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_overview_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title_hash", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary_en", sa.Text(), nullable=False),
        sa.Column("summary_zh", sa.Text(), nullable=False),
        sa.Column("key_topics", sa.JSON(), nullable=False),
        sa.Column("difficulty_hint", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_overview_hash", "article_overview_cache", ["title_hash"], unique=True
    )
    op.create_index(
        op.f("ix_article_overview_cache_title_hash"),
        "article_overview_cache",
        ["title_hash"],
        unique=True,
    )
    op.create_table(
        "sentence_collocation_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sentence_hash", sa.String(length=32), nullable=False),
        sa.Column("sentence_preview", sa.Text(), nullable=False),
        sa.Column("collocations", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_collocation_hash",
        "sentence_collocation_cache",
        ["sentence_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_sentence_collocation_cache_sentence_hash"),
        "sentence_collocation_cache",
        ["sentence_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sentence_collocation_cache_sentence_hash"),
        table_name="sentence_collocation_cache",
    )
    op.drop_index("idx_collocation_hash", table_name="sentence_collocation_cache")
    op.drop_table("sentence_collocation_cache")
    op.drop_index(
        op.f("ix_article_overview_cache_title_hash"),
        table_name="article_overview_cache",
    )
    op.drop_index("idx_overview_hash", table_name="article_overview_cache")
    op.drop_table("article_overview_cache")
    # ### end Alembic commands ###
