"""Add chapters to podcast_episodes

Revision ID: 59ec2718643d
Revises: d95e2a90dfd3
Create Date: 2026-02-02 19:23:36.229520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ec2718643d'
down_revision: Union[str, Sequence[str], None] = 'd95e2a90dfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_episodes', sa.Column('chapters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast_episodes', 'chapters')
    # ### end Alembic commands ###
