"""add duration_ms to review_logs

Revision ID: 5c3ecf488576
Revises: 4f0adbca8a15
Create Date: 2026-01-11 18:05:22.692889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3ecf488576'
down_revision: Union[str, Sequence[str], None] = '4f0adbca8a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = [c['name'] for c in insp.get_columns('reading_sessions')]

    if 'explanation_word_total' in columns:
        op.drop_column('reading_sessions', 'explanation_word_total')
    if 'sentence_click_count' in columns:
        op.drop_column('reading_sessions', 'sentence_click_count')
    if 'sentence_word_total' in columns:
        op.drop_column('reading_sessions', 'sentence_word_total')
    if 'explanation_time_seconds' in columns:
        op.drop_column('reading_sessions', 'explanation_time_seconds')

    op.add_column('review_logs', sa.Column('duration_ms', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_logs', 'duration_ms')
    op.add_column('reading_sessions', sa.Column('explanation_time_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('reading_sessions', sa.Column('sentence_word_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('reading_sessions', sa.Column('sentence_click_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('reading_sessions', sa.Column('explanation_word_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
