"""add_user_comprehension_profile

Revision ID: 72f20468f2be
Revises: 3f9d128aa4e1
Create Date: 2026-01-02 19:19:08.482825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72f20468f2be'
down_revision: Union[str, Sequence[str], None] = '3f9d128aa4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('tense', sa.Text(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('user_response', sa.JSON(), nullable=False),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_activity_type'), 'attempts', ['activity_type'], unique=False)
    op.create_index(op.f('ix_attempts_created_at'), 'attempts', ['created_at'], unique=False)
    op.create_table('user_comprehension_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('cefr_level', sa.Text(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('vocabulary_score', sa.Float(), nullable=False),
    sa.Column('reading_speed_wpm', sa.Integer(), nullable=False),
    sa.Column('listening_comprehension_score', sa.Float(), nullable=False),
    sa.Column('common_grammar_gaps', sa.JSON(), nullable=False),
    sa.Column('weak_vocabulary_topics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comprehension_user', 'user_comprehension_profiles', ['user_id'], unique=True)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('goal_type', sa.Text(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_goals_user', 'user_goals', ['user_id'], unique=False)
    # Use IF EXISTS to handle fresh databases that never had this column
    op.execute("ALTER TABLE sentence_learning_records DROP COLUMN IF EXISTS interaction_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_learning_records', sa.Column('interaction_log', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_index('idx_user_goals_user', table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index('idx_comprehension_user', table_name='user_comprehension_profiles')
    op.drop_table('user_comprehension_profiles')
    op.drop_index(op.f('ix_attempts_created_at'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_activity_type'), table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
