"""add_aui_input_record

Revision ID: a676ad607415
Revises: e8a0aa624b5e
Create Date: 2025-12-25 21:54:22.132447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a676ad607415'
down_revision: Union[str, Sequence[str], None] = 'e8a0aa624b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aui_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aui_input_processed', 'aui_inputs', ['processed'], unique=False)
    op.create_index('idx_aui_input_session', 'aui_inputs', ['session_id'], unique=False)
    op.create_index(op.f('ix_aui_inputs_session_id'), 'aui_inputs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aui_inputs_session_id'), table_name='aui_inputs')
    op.drop_index('idx_aui_input_session', table_name='aui_inputs')
    op.drop_index('idx_aui_input_processed', table_name='aui_inputs')
    op.drop_table('aui_inputs')
    # ### end Alembic commands ###
