"""Add_GeneratedImage_model

Revision ID: a9024f68aa27
Revises: 5c3ecf488576
Create Date: 2026-01-14 19:56:44.626020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9024f68aa27'
down_revision: Union[str, Sequence[str], None] = '5c3ecf488576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('mime_type', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_context_hash'), 'generated_images', ['context_hash'], unique=False)
    op.create_index(op.f('ix_generated_images_word'), 'generated_images', ['word'], unique=False)
    op.create_index('ix_generated_images_word_context', 'generated_images', ['word', 'context_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generated_images_word_context', table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_word'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_context_hash'), table_name='generated_images')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
