"""add_coach_tables

Revision ID: b73c136b5207
Revises: 8a450dbea9be
Create Date: 2025-12-16 10:57:26.223614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b73c136b5207"
down_revision: Union[str, Sequence[str], None] = "8a450dbea9be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coach_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_memories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_memories_key"), "user_memories", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_user_memories_user_id"), "user_memories", ["user_id"], unique=False
    )
    op.create_table(
        "user_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("mastery_level", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "last_practiced",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("practice_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_progress_user_topic", "user_progress", ["user_id", "topic"], unique=False
    )
    op.create_index(
        op.f("ix_attempts_activity_type"), "attempts", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("ix_attempts_created_at"), "attempts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_topic"), "sessions", ["topic"], unique=False)
    op.create_index(
        op.f("ix_srs_schedule_next_review_at"),
        "srs_schedule",
        ["next_review_at"],
        unique=False,
    )
    op.create_index(
        "idx_story_topic_tense", "stories", ["topic", "target_tense"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_story_topic_tense", table_name="stories")
    op.drop_index(op.f("ix_srs_schedule_next_review_at"), table_name="srs_schedule")
    op.drop_index(op.f("ix_sessions_topic"), table_name="sessions")
    op.drop_index(op.f("ix_attempts_created_at"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_activity_type"), table_name="attempts")
    op.drop_index("idx_progress_user_topic", table_name="user_progress")
    op.drop_table("user_progress")
    op.drop_index(op.f("ix_user_memories_user_id"), table_name="user_memories")
    op.drop_index(op.f("ix_user_memories_key"), table_name="user_memories")
    op.drop_table("user_memories")
    op.drop_table("coach_sessions")
    # ### end Alembic commands ###
