"""add sentence_learning_records table

Revision ID: c6f72c1affd5
Revises: db35f242bece
Create Date: 2026-01-01 13:00:09.180763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f72c1affd5'
down_revision: Union[str, Sequence[str], None] = 'db35f242bece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_learning_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('sentence_index', sa.Integer(), nullable=False),
    sa.Column('initial_response', sa.Text(), nullable=False),
    sa.Column('unclear_choice', sa.Text(), nullable=True),
    sa.Column('simplified_response', sa.Text(), nullable=True),
    sa.Column('word_clicks', sa.JSON(), nullable=False),
    sa.Column('dwell_time_ms', sa.Integer(), nullable=False),
    sa.Column('diagnosed_gap_type', sa.Text(), nullable=True),
    sa.Column('diagnosed_patterns', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('scheduled_review', sa.TIMESTAMP(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slr_source_sentence', 'sentence_learning_records', ['source_id', 'sentence_index'], unique=False)
    op.create_index('idx_slr_user_source', 'sentence_learning_records', ['user_id', 'source_type', 'source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_slr_user_source', table_name='sentence_learning_records')
    op.drop_index('idx_slr_source_sentence', table_name='sentence_learning_records')
    op.drop_table('sentence_learning_records')
    # ### end Alembic commands ###
