"""Add file_size to podcast_episodes

Revision ID: d95e2a90dfd3
Revises: c0f6d3834159
Create Date: 2026-02-02 12:57:28.145377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95e2a90dfd3'
down_revision: Union[str, Sequence[str], None] = 'c0f6d3834159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_episodes', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('user_episode_states', 'local_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_episode_states', 'playback_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_episode_states', 'playback_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('user_episode_states', 'local_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('podcast_episodes', 'file_size')
    # ### end Alembic commands ###
