"""Add WordBook and WordBookEntry tables

Revision ID: e2337545152d
Revises: 025f95a766c9
Create Date: 2025-12-27 22:55:46.587274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2337545152d"
down_revision: Union[str, Sequence[str], None] = "025f95a766c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_books",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_word_books_code"), "word_books", ["code"], unique=True)
    op.create_table(
        "word_book_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["word_books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_book_entry_sequence",
        "word_book_entries",
        ["book_id", "sequence"],
        unique=False,
    )
    op.create_index(
        "idx_book_entry_word", "word_book_entries", ["book_id", "word"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_book_entry_word", table_name="word_book_entries")
    op.drop_index("idx_book_entry_sequence", table_name="word_book_entries")
    op.drop_table("word_book_entries")
    op.drop_index(op.f("ix_word_books_code"), table_name="word_books")
    op.drop_table("word_books")
    # ### end Alembic commands ###
