"""add_context_resources_and_learning_records

Revision ID: e8a0aa624b5e
Revises: b73c136b5207
Create Date: 2025-12-24 16:44:57.588968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8a0aa624b5e"
down_revision: Union[str, Sequence[str], None] = "b73c136b5207"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context_resources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("sense_label", sa.Text(), nullable=True),
        sa.Column("context_type", sa.Text(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_context_type", "context_resources", ["context_type"], unique=False
    )
    op.create_index("idx_context_word", "context_resources", ["word"], unique=False)
    op.create_index(
        "idx_context_word_type",
        "context_resources",
        ["word", "context_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_context_resources_word"), "context_resources", ["word"], unique=False
    )
    op.create_table(
        "context_learning_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("last_practiced_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("practice_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_learning_status", "context_learning_records", ["status"], unique=False
    )
    op.create_index(
        "idx_learning_user_context",
        "context_learning_records",
        ["user_id", "context_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_learning_user_context", table_name="context_learning_records")
    op.drop_index("idx_learning_status", table_name="context_learning_records")
    op.drop_table("context_learning_records")
    op.drop_index(op.f("ix_context_resources_word"), table_name="context_resources")
    op.drop_index("idx_context_word_type", table_name="context_resources")
    op.drop_index("idx_context_word", table_name="context_resources")
    op.drop_index("idx_context_type", table_name="context_resources")
    op.drop_table("context_resources")
    # ### end Alembic commands ###
