"""Add article_analysis_failures table

Revision ID: f5fe1073f488
Revises: e29616072000
Create Date: 2026-02-08 21:58:47.241589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5fe1073f488'
down_revision: Union[str, Sequence[str], None] = 'e29616072000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_analysis_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_hash', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_failure_hash', 'article_analysis_failures', ['title_hash'], unique=True)
    op.create_index(op.f('ix_article_analysis_failures_title_hash'), 'article_analysis_failures', ['title_hash'], unique=True)
    op.alter_column('podcast_episodes', 'chapters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcast_episodes', 'chapters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_article_analysis_failures_title_hash'), table_name='article_analysis_failures')
    op.drop_index('idx_analysis_failure_hash', table_name='article_analysis_failures')
    op.drop_table('article_analysis_failures')
    # ### end Alembic commands ###
